### ISSUE TITLE
Theme 

### ISSUE THREAD

**Issue by lorenzo1200** [dbkosky/rofify#1]
How do I install the theme present in the gif?

**Comment by dbkosky** [comment]
I'm really sorry for answering eight months late, it's probably no longer relevant to you, but I figured I'd respond anyway.
You would do it as such
`rofi -modi spotify:"python -m rofify" -show spotify -theme rofify_theme.rasi` 
where `rofify_theme.rasi` is theme file found in the 'themes' directory
